### ISSUE TITLE
终点论坛获取成功签到文本

### ISSUE THREAD

**Issue by lazureice** [LovesAsuna/ForumSignin#10]
OS: linux
chrome-version: Chrome/98 ([headless-shell](https://github.com/chromedp/docker-headless-shell))

签到成功了，但是程序没有退出：
![image](https://user-images.githubusercontent.com/12579737/167420486-8a9a0f58-cbe0-49d0-9307-e68c5477bbf3.png)

https://github.com/LovesAsuna/ForumSignin/issues/7#issuecomment-1114243629
这里说：
> 跑action就会卡住，比如终点签到的goroutine一直卡住不结束

只有action会卡，而本地运行是可以退出的吗？

不懂 chromedp，暂时只能另外写一个 stop 命令……

**Comment by LovesAsuna** [comment]
我目前也是在解决终点模拟摇奖卡住的问题

**Comment by lazureice** [comment]
意思是无论 github action 还是本地运行都不会退出么……好吧。

**Comment by LovesAsuna** [comment]
本地没试过，因为我本地也不是用的Linux

**Comment by lazureice** [comment]
我知道，我就是想问 windows+chrome（有图形界面），程序会不会自动结束。

**Comment by LovesAsuna** [comment]
在我本地里跑，无论有没有图形界面都是正常结束的，所以我暂时没找出在action跑会卡住的原因

**Comment by lazureice** [comment]
今天摇摇出错了，但是网站里却显示签到、摇摇都成功了。看日志，应该是点击摇奖成功了，但是获取结果 `chromedp.InnerHTML(`div #res`, &res)` 失败了。
```
time="2022-05-13T00:01:12Z" level=panic msg="could not retrieve attribute \"innerHTML\": Cannot find context with specified id (-32000)"
panic: (*logrus.Entry) 0xc000132460

goroutine 23 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0001323f0, 0x0, {0xc000274300, 0x58})
        /path/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x43e
github.com/sirupsen/logrus.(*Entry).Log(0xc0001323f0, 0x0, {0xc0000afe48?, 0x10?, 0x8754e0?})
        /path/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Logger).Log(0xc0001320e0, 0x0, {0xc0000afe48, 0x1, 0x1})
        /path/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:198 +0x65
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /path/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:247
github.com/sirupsen/logrus.Panic(...)
        /path/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/exported.go:129
github.com/LovesAsuna/ForumSignin/forum.(*Zdfx).lottery(0xc00014a6c0, {0x9db248, 0xc000180480}, 0x1?)
        /path/ForumSignin/forum/zdfx.go:171 +0x3c5
github.com/LovesAsuna/ForumSignin/forum.(*Zdfx).Sign.func3()
        /path/ForumSignin/forum/zdfx.go:79 +0x1cd
created by github.com/LovesAsuna/ForumSignin/forum.(*Zdfx).Sign
        /path/ForumSignin/forum/zdfx.go:74 +0x178
```
我因为使用headless chrome所以加了几行代码，171行其实是167行：
https://github.com/LovesAsuna/ForumSignin/blob/a542c3cc38f0ed96cc85adfb2c4c97ad63a7e58a/forum/zdfx.go#L167

**Comment by LovesAsuna** [comment]
偶尔会出现的小概率未知问题，应该是网络问题，重新运行应该可以解决。另外不需要特别设置headless，默认这样的

**Comment by lazureice** [comment]
使用 go-versoin 和 [chromedp/docker-headless-shell](https://github.com/chromedp/docker-headless-shell)
连续 3 天没有自动签到了。但输出日志有“已签到”。
> time="2022-05-20T00:01:13Z" level=info msg="已签到"
（东八区是8点）

重新运行也还是一样。

**Comment by LovesAsuna** [comment]
已签到是通过超时重试来完成的，由于是重试了500次，理论上应该是完成了。不过既然出现这种问题，可能还是要考虑获取成功签到的文本来确保完成签到

**Comment by lazureice** [comment]
竟然重试了500次么……因为程序不会自动终止，所以我用 timeout 命令限制运行时间为 100s 。明天签到把这个限制去了再试试。

**Comment by LovesAsuna** [comment]
没办法，chromedp对比selenium，有好的丢放也有不好的地方。对于这里来说，它不好的地方在于如果需要模拟点击的元素不存在，他就会隔50ms不停的重试，而我是则修改了一下逻辑，限制它重试500次，所以最短的话应该有500*50ms那么长了

**Comment by yukimaware** [comment]
最近三四天签到没有成功，可以正常摇一摇，是哪里有问题么？

**Comment by LovesAsuna** [comment]
已经在采用新思路了，过几天就会有成品了

**Comment by lazureice** [comment]
@yukimaware 
我这几天改用action，可以成功签到。

**Comment by LovesAsuna** [comment]
重构完成，可以先行测试一下

**Comment by lazureice** [comment]
第一次签到失败、摇奖成功；第二次签到成功。现在不会再卡住了。
可以根据结果来判断是否要重试了。
```
./ForumSignin
INFO[0009] &{true false}
INFO[0009] <!--[CDATA[Token获取失败]]-->
./ForumSignin
INFO[0002] <!--[CDATA[]]-->
INFO[0002] &{false true}
```

**Comment by LovesAsuna** [comment]
我看了下，第一次签到那个消息确实就是空的，但它是签到成功了，有空我在看看网页的是什么逻辑

**Comment by lazureice** [comment]
昨天签到成功了，今天失败了。注意到一件很奇怪的事：**前面获取到了token，但是签到却提示获取token失败**，有点怪。除此以外日志和昨天的没有不同。
```
time="2022-05-26T00:10:01Z" level=debug msg="开始执行终点的签到操作"
time="2022-05-26T00:10:01Z" level=debug msg="开始执行花火的签到操作"
time="2022-05-26T00:10:01Z" level=info msg="花火Cookie未设置！"
time="2022-05-26T00:10:01Z" level=debug msg="获取终点的hash和token"
time="2022-05-26T00:10:10Z" level=debug msg="终点hash: 21----"
time="2022-05-26T00:10:10Z" level=debug msg="终点token: 03AD-----"（后略）
time="2022-05-26T00:10:10Z" level=debug msg="模拟终点的签到操作"
time="2022-05-26T00:10:10Z" level=debug msg="模拟终点的摇奖操作"
time="2022-05-26T00:10:11Z" level=debug msg="获取终点的签到结果"
time="2022-05-26T00:10:11Z" level=debug msg="Response Body: \ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<root><![CDATA[Token获>取失败]]></root>"
time="2022-05-26T00:10:11Z" level=info msg="<!--[CDATA[Token获取失败]]-->"
time="2022-05-26T00:10:11Z" level=debug msg="获取终点的摇奖结果"
time="2022-05-26T00:10:11Z" level=info msg="摇奖成功，获得点币\n"
```

**Comment by lazureice** [comment]
再签到一次就成功了。
如果 response body 中没有“token获取失败”，签到都是成功的。

```
time="2022-05-27T00:16:11Z" level=debug msg="开始执行终点的签到操作"
time="2022-05-27T00:16:11Z" level=debug msg="开始执行花火的签到操作"
time="2022-05-27T00:16:11Z" level=info msg="花火Cookie未设置！"
time="2022-05-27T00:16:11Z" level=debug msg="获取终点的hash和token"
time="2022-05-27T00:16:20Z" level=debug msg="终点hash: 21---"
time="2022-05-27T00:16:20Z" level=debug msg="终点token: 03AG---"
time="2022-05-27T00:16:20Z" level=debug msg="模拟终点的签到操作"
time="2022-05-27T00:16:20Z" level=debug msg="模拟终点的摇奖操作"
time="2022-05-27T00:16:21Z" level=debug msg="获取终点的签到结果"
time="2022-05-27T00:16:21Z" level=debug msg="Response Body: <?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<root><![CDATA[]]></root>"
time="2022-05-27T00:16:21Z" level=info msg="<!--[CDATA[]]-->"
time="2022-05-27T00:16:21Z" level=debug msg="获取终点的摇奖结果"
time="2022-05-27T00:16:21Z" level=info msg="你已经摇过奖了"
```

**Comment by LovesAsuna** [comment]
目前还不清楚为什么第一次会出现token获取失败
